import numpy as np
from ..base import Layer
from neutro.autograd import Tensor
from neutro.autograd.function import Function


class ReparameterizationFunction(Function):
    """
    z = z_mean + exp(0.5 * z_log_var) * epsilon    (epsilon ~ N(0, 1))

    Reparameterization trick: makes sampling differentiable.
    Epsilon is generated by the layer and passed in to keep the
    random value accessible (e.g. for gradient verification).
    """
    @staticmethod
    def forward(ctx, z_mean, z_log_var, epsilon):
        ctx.save_for_backward(epsilon=epsilon, z_log_var=z_log_var)
        return z_mean + np.exp(0.5 * z_log_var) * epsilon

    @staticmethod
    def backward(ctx, grad_output):
        epsilon = ctx.saved_data['epsilon']
        z_log_var = ctx.saved_data['z_log_var']
        grad_mean = grad_output
        grad_log_var = grad_output * np.exp(0.5 * z_log_var) * 0.5 * epsilon
        return grad_mean, grad_log_var, None


class Reparameterization(Layer):
    """
    VAE reparameterization trick: z = z_mean + exp(0.5 * z_log_var) * epsilon.

    Input:  list of [z_mean (B, D), z_log_var (B, D)]
    Output: (B, D) — sampled latent code (or z_mean in eval mode)
    """

    def compute_output_shape(self, input_shape):
        if isinstance(input_shape, list):
            return input_shape[0]
        return input_shape

    def forward(self, inputs, training=False):
        z_mean, z_log_var = inputs
        if not training:
            self.epsilon = None
            return z_mean
        self.epsilon = np.random.normal(size=z_mean.shape)
        return ReparameterizationFunction.apply(z_mean, z_log_var, self.epsilon)
